sudo: false
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script:
    - echo "twitterConsumerKey=$TWITTER_CONSUMER_KEY" >> samples/app/fabric.properties
    - echo "twitterConsumerSecret=$TWITTER_CONSUMER_SECRET" >> samples/app/fabric.properties
    - echo "apiKey=$API_KEY" >> samples/app/fabric.properties
    - echo "apiSecret=$API_SECRET" >> samples/app/fabric.properties
    - ./gradlew assemble test
